// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// simFish
NumericMatrix simFish(int numSims, int numYears, double targetER, bool managementError, double manageErrorA, double manageErrorB, String errorType, double SRerrorA, double SRerrorB, NumericVector initPop, double prod, double cap, NumericVector mat, NumericVector mort, NumericVector HRpt, NumericVector HRt, NumericVector AEQ);
RcppExport SEXP _VRAPCpp_simFish(SEXP numSimsSEXP, SEXP numYearsSEXP, SEXP targetERSEXP, SEXP managementErrorSEXP, SEXP manageErrorASEXP, SEXP manageErrorBSEXP, SEXP errorTypeSEXP, SEXP SRerrorASEXP, SEXP SRerrorBSEXP, SEXP initPopSEXP, SEXP prodSEXP, SEXP capSEXP, SEXP matSEXP, SEXP mortSEXP, SEXP HRptSEXP, SEXP HRtSEXP, SEXP AEQSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type numSims(numSimsSEXP);
    Rcpp::traits::input_parameter< int >::type numYears(numYearsSEXP);
    Rcpp::traits::input_parameter< double >::type targetER(targetERSEXP);
    Rcpp::traits::input_parameter< bool >::type managementError(managementErrorSEXP);
    Rcpp::traits::input_parameter< double >::type manageErrorA(manageErrorASEXP);
    Rcpp::traits::input_parameter< double >::type manageErrorB(manageErrorBSEXP);
    Rcpp::traits::input_parameter< String >::type errorType(errorTypeSEXP);
    Rcpp::traits::input_parameter< double >::type SRerrorA(SRerrorASEXP);
    Rcpp::traits::input_parameter< double >::type SRerrorB(SRerrorBSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type initPop(initPopSEXP);
    Rcpp::traits::input_parameter< double >::type prod(prodSEXP);
    Rcpp::traits::input_parameter< double >::type cap(capSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mort(mortSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type HRpt(HRptSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type HRt(HRtSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type AEQ(AEQSEXP);
    rcpp_result_gen = Rcpp::wrap(simFish(numSims, numYears, targetER, managementError, manageErrorA, manageErrorB, errorType, SRerrorA, SRerrorB, initPop, prod, cap, mat, mort, HRpt, HRt, AEQ));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _VRAP-C_simFish(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_VRAPCpp_simFish", (DL_FUNC) &_VRAPCpp_simFish, 17},
    {"_VRAP-C_simFish", (DL_FUNC) &_VRAP-C_simFish, 17},
    {NULL, NULL, 0}
};

RcppExport void R_init_VRAPCpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
