// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// simFish
List simFish(int NRuns, int NYears, double targetER, bool MgmtError, double GammaMgmtA, double GammaMgmtB, String errorType, double SRErrorA, double SRErrorB, NumericVector CohortStart, double prod, double cap, NumericVector MatRate, NumericVector NatMort, NumericVector PTU, NumericVector MatU, NumericVector AEQ);
RcppExport SEXP _VRAPS_simFish(SEXP NRunsSEXP, SEXP NYearsSEXP, SEXP targetERSEXP, SEXP MgmtErrorSEXP, SEXP GammaMgmtASEXP, SEXP GammaMgmtBSEXP, SEXP errorTypeSEXP, SEXP SRErrorASEXP, SEXP SRErrorBSEXP, SEXP CohortStartSEXP, SEXP prodSEXP, SEXP capSEXP, SEXP MatRateSEXP, SEXP NatMortSEXP, SEXP PTUSEXP, SEXP MatUSEXP, SEXP AEQSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type NRuns(NRunsSEXP);
    Rcpp::traits::input_parameter< int >::type NYears(NYearsSEXP);
    Rcpp::traits::input_parameter< double >::type targetER(targetERSEXP);
    Rcpp::traits::input_parameter< bool >::type MgmtError(MgmtErrorSEXP);
    Rcpp::traits::input_parameter< double >::type GammaMgmtA(GammaMgmtASEXP);
    Rcpp::traits::input_parameter< double >::type GammaMgmtB(GammaMgmtBSEXP);
    Rcpp::traits::input_parameter< String >::type errorType(errorTypeSEXP);
    Rcpp::traits::input_parameter< double >::type SRErrorA(SRErrorASEXP);
    Rcpp::traits::input_parameter< double >::type SRErrorB(SRErrorBSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type CohortStart(CohortStartSEXP);
    Rcpp::traits::input_parameter< double >::type prod(prodSEXP);
    Rcpp::traits::input_parameter< double >::type cap(capSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type MatRate(MatRateSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type NatMort(NatMortSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type PTU(PTUSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type MatU(MatUSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type AEQ(AEQSEXP);
    rcpp_result_gen = Rcpp::wrap(simFish(NRuns, NYears, targetER, MgmtError, GammaMgmtA, GammaMgmtB, errorType, SRErrorA, SRErrorB, CohortStart, prod, cap, MatRate, NatMort, PTU, MatU, AEQ));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_VRAPS_simFish", (DL_FUNC) &_VRAPS_simFish, 17},
    {NULL, NULL, 0}
};

RcppExport void R_init_VRAPS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
