# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simFish <- function(numSims, numYears, targetER, managementError, manageErrorA, manageErrorB, errorType, SRerrorA, SRerrorB, initPop, prod, cap, mat, mort, HRpt, HRt, AEQ) {
    .Call(`_VRAPCpp_simFish`, numSims, numYears, targetER, managementError, manageErrorA, manageErrorB, errorType, SRerrorA, SRerrorB, initPop, prod, cap, mat, mort, HRpt, HRt, AEQ)
}

